export const sharedStyles = {
    page: {
        minHeight:       "100vh",
        backgroundColor: "#0a0e0a",
        display:         "flex",
        alignItems:      "center",
        justifyContent:  "center",
        fontFamily:      "'Segoe UI', sans-serif",
        position:        "relative",
        overflow:        "hidden",
    },
    grid: {
        position:        "absolute",
        inset:           0,
        backgroundImage: `
            linear-gradient(rgba(0,200,83,0.04) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0,200,83,0.04) 1px, transparent 1px)
        `,
        backgroundSize: "40px 40px",
        pointerEvents:  "none",
    },
    card: {
        backgroundColor: "#111711",
        border:          "1px solid #1e2e1e",
        borderRadius:    30,
        padding:         "40px 36px",
        width:           "100%",
        maxWidth:        440,
        position:        "relative",
        zIndex:          1,
        boxShadow:       "0 0 60px rgba(0,200,83,0.06)",
    },
    iconWrap: {
        width:           52,
        height:          52,
        borderRadius:    "50%",
        border:          "2px solid #165b33",
        display:         "flex",
        alignItems:      "center",
        justifyContent:  "center",
        margin:          "0 auto 16px",
        backgroundColor: "rgba(0,200,83,0.08)",
    },
    icon: {
        fontSize: 22,
        color:    "#165b33",
    },
    title: {
        color:         "#ffffff",
        fontSize:      20,
        fontWeight:    700,
        textAlign:     "center",
        margin:        "0 0 6px",
        letterSpacing: 1.5,
    },
    subtitle: {
        color:        "#6b7c6b",
        fontSize:     13,
        textAlign:    "center",
        marginBottom: 28,
    },
    alert: {
        marginBottom:    16,
        backgroundColor: "rgba(255,77,79,0.1)",
        color:           "white",
        border:          "1px solid rgba(255,77,79,0.3)",
        borderRadius:    6,
    },
    inputIcon: {
        color: "#555",
    },
    input: {
        backgroundColor: "#0d130d",
        border:          "1px solid #1e2e1e",
        borderRadius:    6,
        color:           "#d0e8d0",
        height:          44,
    },
    button: {
        backgroundColor: "#348355",
        border:          "none",
        borderRadius:    6,
        height:          46,
        fontSize:        15,
        fontWeight:      700,
        letterSpacing:   0.5,
        color:           "#000",
        marginTop:       4,
    },
    invalidBox: {
        textAlign: "center",
        padding:   "20px 0",
    },
    invalidText: {
        color:      "#4a5e4a",
        fontSize:   13,
        lineHeight: 1.6,
    },
}

export const loginStyles = {
    row: {
        display:        "flex",
        justifyContent: "space-between",
        alignItems:     "center",
        marginBottom:   20,
        marginTop:      -8,
    },
    checkbox: {
        color:    "#6b7c6b",
        fontSize: 13,
    },
    forgot: {
        color:      "#348355",
        fontSize:   13,
        fontWeight: 500,
    },
    dividerRow: {
        display:    "flex",
        alignItems: "center",
        margin:     "24px 0 16px",
        gap:        10,
    },
    dividerLine: {
        flex:            1,
        height:          1,
        backgroundColor: "#1e2e1e",
    },
    dividerText: {
        color:         "#3a4e3a",
        fontSize:      11,
        whiteSpace:    "nowrap",
        letterSpacing: 1,
    },
    ssoButton: {
        backgroundColor: "#0d130d",
        border:          "1px solid #1e2e1e",
        borderRadius:    6,
        color:           "#6b7c6b",
        height:          44,
        fontSize:        13,
    },
    footer: {
        display:         "flex",
        alignItems:      "flex-start",
        marginTop:       24,
        padding:         "12px 14px",
        borderRadius:    6,
        border:          "1px solid #1a2a1a",
        backgroundColor: "#0d130d",
        gap:             6,
    },
    footerText: {
        color:      "#4a5e4a",
        fontSize:   12,
        lineHeight: 1.5,
    },
}