export const sharedStyles = {
    page: {
        height:          '100vh',
        backgroundColor: '#f5f7f5',
        width:           '100%',
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        fontFamily:      "'Segoe UI', sans-serif",
        position:        'relative',
        overflow:        'hidden',
        padding:         '0 16px',
    },
    grid: {
        position:        'absolute',
        inset:           0,
        backgroundImage: `
            linear-gradient(rgba(52,131,85,0.06) 1px, transparent 1px),
            linear-gradient(90deg, rgba(52,131,85,0.06) 1px, transparent 1px)
        `,
        backgroundSize: '40px 40px',
        pointerEvents:  'none',
    },
    card: {
        backgroundColor: '#ffffff',
        border:          '1px solid #d4e0d4',
        borderRadius:    10,
        padding:         '28px 36px',
        width:           '100%',
        maxWidth:        '650px',
        maxHeight:       'calc(100vh - 40px)',
        overflowY:       'auto',
        position:        'relative',
        zIndex:          1,
        boxShadow:       '0 4px 24px rgba(52,131,85,0.08), 0 1px 4px rgba(0,0,0,0.04)',
        scrollbarWidth:  'none',
        msOverflowStyle: 'none',
    },
    iconWrap: {
        width:           44,
        height:          44,
        borderRadius:    '50%',
        border:          '2px solid #348355',
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        margin:          '0 auto 12px',
        backgroundColor: '#e8f5ee',
    },
    icon: {
        fontSize: 20,
        color:    '#348355',
    },
    title: {
        color:         '#1a2e1a',
        fontSize:      20,
        fontWeight:    700,
        textAlign:     'center',
        margin:        '0 0 4px',
        letterSpacing: 1.5,
    },
    subtitle: {
        color:        '#5a7a5a',
        fontSize:     13,
        textAlign:    'center',
        marginBottom: 20,
    },
    alert: {
        marginBottom:    16,
        backgroundColor: 'rgba(211,47,47,0.06)',
        color:           '#d32f2f',
        border:          '1px solid rgba(211,47,47,0.2)',
        borderRadius:    6,
    },
    inputIcon: {
        color: '#8aaa8a',
    },
    input: {
        backgroundColor: '#f0f4f0',
        border:          '1px solid #d4e0d4',
        borderRadius:    6,
        color:           '#1a2e1a',
        height:          40,
        PointerEvent:    "none"
    },
    button: {
        backgroundColor: '#348355',
        border:          'none',
        borderRadius:    6,
        height:          44,
        fontSize:        15,
        fontWeight:      700,
        letterSpacing:   0.5,
        color:           '#ffffff',
        marginTop:       4,
    },
    invalidBox: {
        textAlign: 'center',
        padding:   '20px 0',
    },
    invalidText: {
        color:      '#5a7a5a',
        fontSize:   13,
        lineHeight: 1.6,
    },
}

export const loginStyles = {
    row: {
        display:        'flex',
        justifyContent: 'space-between',
        alignItems:     'center',
        marginBottom:   20,
        marginTop:      -8,
    },
    checkbox: {
        color:    '#5a7a5a',
        fontSize: 13,
    },
    forgot: {
        color:      '#348355',
        fontSize:   13,
        fontWeight: 500,
    },
    dividerRow: {
        display:     'flex',
        alignItems:  'center',
        margin:      '20px 0 14px',
        gap:         10,
        borderColor: '#d4e0d4',
    },
    dividerText: {
        color:         '#8aaa8a',
        fontSize:      11,
        whiteSpace:    'nowrap',
        letterSpacing: 1,
    },
    footer: {
        display:         'flex',
        alignItems:      'flex-start',
        marginTop:       20,
        padding:         '12px 14px',
        borderRadius:    6,
        border:          '1px solid #d4e0d4',
        backgroundColor: '#f0f4f0',
        gap:             6,
    },
    footerText: {
        color:      '#5a7a5a',
        fontSize:   12,
        lineHeight: 1.5,
    },

    stepDotActive: {
        width:           26,
        height:          26,
        borderRadius:    '50%',
        flexShrink:      0,
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        fontSize:        11,
        fontWeight:      700,
        backgroundColor: '#348355',
        border:          '1.5px solid #348355',
        color:           '#fff',
        transition:      'all 0.3s',
    },
    stepDotDone: {
        width:           26,
        height:          26,
        borderRadius:    '50%',
        flexShrink:      0,
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        fontSize:        11,
        fontWeight:      700,
        backgroundColor: '#348355',
        border:          '1.5px solid #348355',
        color:           '#fff',
        transition:      'all 0.3s',
    },
    stepDotInactive: {
        width:           26,
        height:          26,
        borderRadius:    '50%',
        flexShrink:      0,
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        fontSize:        11,
        fontWeight:      700,
        backgroundColor: 'transparent',
        border:          '1.5px solid #d4e0d4',
        color:           '#8aaa8a',
        transition:      'all 0.3s',
    },
    stepConnectorActive: {
        flex:            1,
        height:          1.5,
        borderRadius:    2,
        backgroundColor: '#348355',
        transition:      'background-color 0.3s',
    },
    stepConnectorInactive: {
        flex:            1,
        height:          1.5,
        borderRadius:    2,
        backgroundColor: '#d4e0d4',
        transition:      'background-color 0.3s',
    },
    stepLabel: {
        color:         '#8aaa8a',
        fontSize:      10,
        fontWeight:    600,
        letterSpacing: 2,
        textTransform: 'uppercase',
        margin:        '0 0 3px',
    },
    stepTitle: {
        color:      '#1a2e1a',
        fontSize:   16,
        fontWeight: 700,
        margin:     '0 0 2px',
    },
    stepSub: {
        color:    '#5a7a5a',
        fontSize: 12,
        margin:   0,
    },

    otpMailWrap: {
        width:           56,
        height:          56,
        borderRadius:    '50%',
        border:          '1.5px solid #d4e0d4',
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        margin:          '0 auto 12px',
        backgroundColor: '#e8f5ee',
    },
    otpText: {
        color:        '#1a2e1a',
        fontSize:     13,
        marginBottom: 3,
    },
    otpEmail: {
        color:        '#348355',
        fontWeight:   700,
        fontSize:     14,
        marginBottom: 3,
    },
    otpHint: {
        color:    '#5a7a5a',
        fontSize: 12,
        margin:   0,
    },
    otpError: {
        color:    '#d32f2f',
        fontSize: 13,
        margin:   '-6px 0 12px',
    },
    otpResendText: {
        color:    '#5a7a5a',
        fontSize: 13,
    },
    otpCountdown: {
        color:      '#348355',
        fontWeight: 600,
    },
    otpDigitFilled: {
        width:           48,
        height:          54,
        textAlign:       'center',
        fontSize:        22,
        fontWeight:      700,
        backgroundColor: '#e8f5ee',
        border:          '1.5px solid #348355',
        borderRadius:    10,
        color:           '#1a2e1a',
        outline:         'none',
        transition:      'all 0.15s ease',
        caretColor:      '#348355',
        boxShadow:       '0 0 0 3px rgba(52,131,85,0.12)',
    },
    otpDigitEmpty: {
        width:           48,
        height:          54,
        textAlign:       'center',
        fontSize:        22,
        fontWeight:      700,
        backgroundColor: '#f0f4f0',
        border:          '1.5px solid #d4e0d4',
        borderRadius:    10,
        color:           '#1a2e1a',
        outline:         'none',
        transition:      'all 0.15s ease',
        caretColor:      '#348355',
        boxShadow:       'none',
    },

    fieldLabel: {
        color:      '#5a7a5a',
        fontSize:   13,
        fontWeight: 500,
    },

    infoBox: {
        padding:         '10px 14px',
        borderRadius:    8,
        backgroundColor: '#f0f4f0',
        border:          '1px solid #d4e0d4',
        marginBottom:    16,
    },
    infoBoxText: {
        color:      '#5a7a5a',
        fontSize:   12,
        margin:     0,
        lineHeight: 1.7,
    },

    backButton: {
        backgroundColor: 'transparent',
        borderColor:     '#d4e0d4',
        color:           '#5a7a5a',
        borderRadius:    8,
        height:          40,
    },
    nextButton: {
        backgroundColor: '#348355',
        border:          'none',
        borderRadius:    8,
        height:          40,
        paddingInline:   24,
        fontWeight:      700,
        fontSize:        14,
        color:           '#fff',
        transition:      'opacity 0.2s',
    },

    selectDropdown: {
        backgroundColor: '#ffffff',
        border:          '1px solid #d4e0d4',
    },

    successIconWrap: {
        width:           64,
        height:          64,
        borderRadius:    '50%',
        border:          '2px solid #348355',
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        margin:          '0 auto 20px',
        backgroundColor: '#e8f5ee',
        boxShadow:       '0 0 32px rgba(52,131,85,0.15)',
    },
    successTitle: {
        color:         '#1a2e1a',
        fontSize:      22,
        fontWeight:    700,
        margin:        '0 0 8px',
        letterSpacing: 0.5,
    },
    successSub: {
        color:      '#5a7a5a',
        fontSize:   14,
        lineHeight: 1.8,
        margin:     0,
    },
    successEmail: {
        color:      '#348355',
        fontWeight: 600,
    },
    successNote: {
        margin:          '24px 0',
        padding:         '14px 16px',
        borderRadius:    8,
        backgroundColor: '#f0f4f0',
        border:          '1px solid #d4e0d4',
    },
    successNoteText: {
        color:      '#8aaa8a',
        fontSize:   12,
        margin:     0,
        lineHeight: 1.7,
    },
    successBtn: {
        width:           '100%',
        height:          46,
        backgroundColor: '#348355',
        border:          'none',
        borderRadius:    8,
        fontSize:        15,
        fontWeight:      700,
        color:           '#fff',
    },
}