export const S = {
    root: {
        minHeight:  "100vh",
        background: "#f5f6fa",
        fontFamily: "'Segoe UI', sans-serif",
    },
    sider: {
        height:        "100vh",
        position:      "fixed",
        left: 0, top: 0, bottom: 0,
        zIndex:        1000,
        background:    "#173117",
        borderRight:   "1px solid #084308d5",
        overflow:      "hidden",
    },
    siderInner: {
        display:        "flex",
        flexDirection:  "column",
        height:         "100%",  
    },
    logo: {
        padding:    "20px 16px 12px",
        minHeight:  52,
        flexShrink: 0,
    },
    logoTitle: {
        color:      "#f5f6fa",
        fontWeight: 700,
        fontSize:   13,
    },
    menuLabel: {
        color:         "#bfbfbf",
        fontSize:      9,
        padding:       "8px 16px 15px",
        letterSpacing: 1,
    },
    menuWrapper: {
        flex:     1,       
        overflow: "hidden",
    },
    menu: {
        background: "transparent",
        border:     "none",
    },
    userBox: {
        display:     "flex",
        alignItems:  "center",
        gap:         8,
        padding:     "14px 16px",
        flexShrink:  0,
        borderTop:   "1px solid rgba(255,255,255,0.08)",
    },
    avatar:   { background: "#1c3251", fontSize: 12, flexShrink: 0 },
    userName: { color: "#f0f0f0", fontSize: 13, fontWeight: 600, lineHeight: 1.3 },
    userRole: { color: "#9e9e9e", fontSize: 9 },
    header: {
        background:     "#ffffff",
        borderBottom:   "1px solid #f0f0f0",
        padding:        "0 20px",
        height:         68,
        display:        "flex",
        alignItems:     "center",
        justifyContent: "space-between",
        boxShadow:      "0 1px 4px rgba(0,0,0,0.04)",
        position:       "sticky",
        top:            0,
        zIndex:         100,
    },
    headerTitle: {
        fontFamily: "'Times New Roman', Times, serif",
        fontWeight: "bold",
        color:      "#0f0f14",
        fontSize:   17,
        margin:     0,
    },
    headerRight: { display: "flex", alignItems: "center", gap: 10 },
    datePicker:  { background: "#fff", border: "1px solid #d9d9d9", borderRadius: 6 },
    iconBtn:     { background: "#fff", border: "1px solid #d9d9d9", color: "#595959" },
    content:     { padding: "20px 24px" },
    statCard: {
        background:   "#fff",
        border:       "1px solid #f0f0f0",
        borderRadius: 8,
        boxShadow:    "0 1px 4px rgba(0,0,0,0.04)",
    },
    statIcon: (color) => ({
        width:          32,
        height:         32,
        borderRadius:   6,
        background:     `${color}18`,
        color,
        display:        "flex",
        alignItems:     "center",
        justifyContent: "center",
        fontSize:       14,
        marginBottom:   8,
    }),
    statLabel:  { color: "#8c8c8c", fontSize: 11 },
    statValue:  { color: "#1a1a2e", fontSize: 20, fontWeight: 700 },
    statChange: (up) => ({
        color:     up ? "#066c06" : "#ff4d4f",
        fontSize:  11,
        marginTop: 4,
    }),
    card: {
        background:   "#fff",
        border:       "1px solid #f0f0f0",
        borderRadius: 8,
        boxShadow:    "0 1px 4px rgba(0,0,0,0.04)",
    },
    cardTitle: { color: "#1a1a2e", fontWeight: 600, fontSize: 14 },
    legendItem: { display: "flex", alignItems: "center", gap: 5, marginBottom: 12 },
    legendDot:  (color) => ({
        width:        14,
        height:       14,
        borderRadius: "50%",
        background:   color,
        flexShrink:   0,
    }),
    legendText: { color: "#595959", fontSize: 12, marginTop: "2px" },
    alertItem: {
        display:      "flex",
        alignItems:   "flex-start",
        gap:          10,
        padding:      "10px 0",
        borderBottom: "1px solid #f5f5f5",
    },
    alertIcon: (type) => ({
        width:          28,
        height:         28,
        borderRadius:   "50%",
        flexShrink:     0,
        marginTop:      2,
        background:     type === "error" ? "#fff1f0" : "#fffbe6",
        color:          type === "error" ? "#ff4d4f" : "#faad14",
        display:        "flex",
        alignItems:     "center",
        justifyContent: "center",
        fontSize:       12,
    }),
    alertTitle: { color: "#1a1a2e", fontSize: 12, fontWeight: 600 },
    alertSub:   { color: "#8c8c8c", fontSize: 11 },
    alertTime:  { color: "#bfbfbf", fontSize: 10, whiteSpace: "nowrap", marginTop: 2 },
    merchantRow: {
        display:      "flex",
        alignItems:   "center",
        padding:      "8px 0",
        borderBottom: "1px solid #f5f5f5",
    },
    merchantRank: { color: "#bfbfbf", fontSize: 12, width: 20, flexShrink: 0 },
    merchantName: { color: "#595959", fontSize: 12, flex: 1 },
    merchantVol:  { color: "#1a1a2e", fontSize: 12, fontWeight: 600 },
    statusRow:    { display: "flex", justifyContent: "space-between", alignItems: "center" },
    txnId:        { color: "#1677ff", fontSize: 12, fontFamily: "monospace" },
    tableText:    { color: "#222121", fontSize: 12 },
    amount:       { color: "#1a1a2e", fontSize: 12, fontWeight: 600 },
    timeText:     { color: "#bfbfbf", fontSize: 11 },
}