# Generated by Django 6.0.5 on 2026-06-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terminal', '0001_initial'),
        ('Transactions', '0003_transaction_device_id_transaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Terminal.terminal'),
        ),
    ]
