# Generated by Django 6.0.5 on 2026-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FraudRules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagrule',
            name='rule_type',
            field=models.CharField(choices=[('amount_threshold', 'Amount Threshold'), ('frequency', 'Frequency'), ('velocity', 'Velocity'), ('duplicate', 'Duplicate'), ('geo_mismatch', 'Geo Mismatch'), ('device_change', 'Device Change'), ('night_activity', 'Night Activity'), ('failed_transactions', 'Failed Transactions')], max_length=50),
        ),
    ]
