# Generated by Django 6.0.5 on 2026-06-02 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Merchants', '0004_remove_merchant_first_name_remove_merchant_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('terminal_type', models.CharField(choices=[('pos', 'POS'), ('web', 'Web Terminal'), ('mobile', 'Mobile')], default='pos', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('maintenance', 'Maintainance')], default='active', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('supervisor_pin', models.CharField(blank=True, help_text='Hashed PIN', max_length=100)),
                ('pin_reset_required', models.BooleanField(default=True)),
                ('per_transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('enforce_limits', models.BooleanField(default=True)),
                ('allow_transfers', models.BooleanField(default=True)),
                ('allow_withdrawals', models.BooleanField(default=True)),
                ('allow_airtime', models.BooleanField(default=True)),
                ('allow_bill_payment', models.BooleanField(default=True)),
                ('allow_pos_purchase', models.BooleanField(default=True)),
                ('allow_reversal', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_terminals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terminals', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals', to='Merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_assignments', to=settings.AUTH_USER_MODEL)),
                ('from_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals_sent', to='Merchants.merchant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='Terminal.terminal')),
                ('to_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminals_received', to='Merchants.merchant')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
