# Generated by Django 6.0.5 on 2026-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
