# Generated by Django 6.0.5 on 2026-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoruser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Monitor User', 'verbose_name_plural': 'Monitor Users'},
        ),
        migrations.AlterField(
            model_name='monitoruser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', 'Operator'), ('user', 'User')], default='operator', max_length=20),
        ),
    ]
