# Generated by Django 6.0.5 on 2026-05-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.monitoruser',),
        ),
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Operator / Admin',
                'verbose_name_plural': 'Operators & Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.monitoruser',),
        ),
    ]
