# Generated by Django 6.0.5 on 2026-06-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchants', '0003_merchant_first_name_merchant_last_name_merchant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_name',
        ),
    ]
